spring:
  application:
    name: app-small-crm
  datasource:
    url: jdbc:postgresql://postgres:5432/crm
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8085

app:
  jwt:
    access:
      secretKey: 3crt346ef14937c1c0ea519f8fc123a80fcd04a7420f8e8bcd0a7567c272e007b
      expirationAt: 3000000
    refresh:
      secretKey: 1abc346ef14937c1c0ea519f8fc123a80fcd04a7420f8e8bcd0a7567c272e007b
      expirationAt: 9000000